services:
  servicio-libros:
    build:
      context: ./ServicioLibros
      dockerfile: Dockerfile
    container_name: servicio-libros
    ports:
      - "8082:8082"
    networks:
      - app-network
    restart: unless-stopped

  servicio-calificaciones:
    build:
      context: ./ServicioGestionCalificaciones
      dockerfile: Dockerfile
    container_name: servicio-calificaciones
    ports:
      - "8081:8081"
    networks:
      - app-network
    restart: unless-stopped

  scientific-calculations:
    build:
      context: ./ScientificCalculations
      dockerfile: Dockerfile
    container_name: scientific-calculations
    ports:
      - "8083:8083"
    networks:
      - app-network
    restart: unless-stopped

  mvc-frontend:
    build:
      context: ./MVC
      dockerfile: Dockerfile
    container_name: mvc-frontend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - servicio-libros
      - servicio-calificaciones
      - scientific-calculations
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
